#ifndef _DEFINES_H
#define _DEFINES_H

#define PRF 4e6
#define SAMPLE_RATE 64e6
#define DECIM_FACTOR 33
#define START_LO_FREQ 5.312e9
#define IF_FREQ 990e6
#define STEP_FREQ (-32e6)
#define TUNE_OFFSET 42e3
#define USE_IMAGE true

#define RECORD_TICKS 35000
#define TOTAL_TICKS (RECORD_TICKS + 1 + 642 + 31)
#define NUM_STEPS 32
#define TICKS_PER_SEQUENCE (4096 + TOTAL_TICKS * NUM_STEPS)
#define STREAM_DECIM 33
#define SAMPLES_PER_FREQ (int)(TOTAL_TICKS/STREAM_DECIM)
#define SKIP_SAMPLES 240
#define SAMPLES_PER_TRIMMED_STEP (SAMPLES_PER_FREQ-SKIP_SAMPLES-59)
#define SAMPLES_PER_SEQ (SAMPLES_PER_FREQ*NUM_STEPS+1)
#define FFT_SIZE 782
#define NUM_HARMONICS_PER_STEP 16
#define HARMONIC_NON_OVERLAP_START 4
#define HARMONIC_NON_OVERLAP_END 11
#define NUM_HARM_PER_STEP_POST (HARMONIC_NON_OVERLAP_END-HARMONIC_NON_OVERLAP_START+1)
#define FFT_SIZE_POST (NUM_STEPS*NUM_HARM_PER_STEP_POST)

#define NUM_ANCHORS 4
#define PRF_EST_ANCHOR 0

#define NUM_HIST 10

#define PRF_ACCURACY 20e-6
#define COARSE_PRECISION 1e-7
#define FINE_PRECISION 1e-9

#define INTERP 64

#define POW2_CEIL(x) ((int)pow(2,ceil(log2(x))))

#endif
