#ifndef _DEFINES_H
#define _DEFINES_H

#define RECORD_TICKS 35000
#define TOTAL_TICKS RECORD_TICKS + 1 + 642 + 31
#define TICKS_PER_SEQUENCE 4096 + TOTAL_TICKS * 32
#define STREAM_DECIM 33
#define SAMPLES_PER_FREQ (int)(TOTAL_TICKS/STREAM_DECIM)
#define SKIP_SAMPLES 240
#define SAMPLES_PER_TRIMMED_STEP SAMPLES_PER_FREQ-SKIP_SAMPLES-59;
#define NUM_STEPS 32
#define SAMPLES_PER_SEQ SAMPLES_PER_FREQ*NUM_STEPS+1
#define FFT_SIZE 782
#define NUM_HARMONICS_PER_STEP 16

#define PRF_EST_ANCHOR 0

#define NUM_HIST 10

#define COARSE_PRECISION 1e-7
#define FINE_PRECISION 1e-9

#define INTERP 64

#endif
